---

# Credenciales para la conexion de wordpress con postgresql
db_name: wordpress
db_user: wordpress


# Version de wordpress
version_wordpress: latest  # wordpress-5.1.6


grupo_apache: apache

...