---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  vars_files:
    - main.yml
  tasks:
    - name: Iniciar servicio 
      ansible.builtin.service:
        name: "{{ servicio }}"
        state: started
      register: status
  

    - name: Comprobar servicio
      ansible.builtin.assert:
        that: not status.changed
        success_msg: "{{ servicio }} corriendo"
        fail_msg: "{{ servicio }} no esta corriendo"


    - name: crear fichero en /var/www/html/
      ansible.builtin.copy:
        dest: /var/www/html/prueba.html
        content: "Fichero prueba para verify ansible"


    - name: Comprobar conexion a pagina de apache
      ansible.builtin.uri:
        url: http://localhost:8080/prueba.html
      register: pagina


    - name: Comprobar codigo http
      ansible.builtin.assert:
        that: pagina.status == 200
        success_msg: "{{ servicio }} funcionando correctamente"
        fail_msg: "{{ servicio }} no esta funcionando correctamente"


    - name: Eliminar fichero prueba.html
      ansible.builtin.file:
        path: /var/www/html/prueba.html
        state: absent        

...